[Unit]
After=onescan-open-api.service

[Service]
WorkingDirectory=/opt/onescan/current/backend
Environment=ONESCAN_API_URL=http://127.0.0.1:8001
Environment=PROXANT_AUTH_HELPER_PATH=/opt/rppg-toolbox/api
ExecStart=
ExecStart=/opt/rppg-toolbox/.venv/bin/streamlit run /opt/onescan/current/backend/streamlit_app.py --server.port 8501 --server.address 127.0.0.1 --server.headless true
